f = open("archivo.txt", "a")
f.write("hola\n")
f.write("desde un archivo\n")
f.write(":p\n")
f.close()
f = open("archivo.txt", "r")
print(f.read())
f.close()
f = open("archivo.txt", "a")
f.write("hola2\n")
f.write("desde el mismo archivo\n")
f.write(":D\n")
f.close()
f = open("archivo.txt", "r")
print(f.read())
f.close()
